name: bowtie2_align
description: Align reads to a reference genome using bowtie2
keywords:
    - align
    - fasta
    - genome
    - reference
tools:
    - bowtie2:
          description: |
              Bowtie 2 is an ultrafast and memory-efficient tool for aligning
              sequencing reads to long reference sequences.
          homepage: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml
          documentation: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
          doi: 10.1038/nmeth.1923
input:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
    - reads:
          type: file
          description: |
              List of input FastQ files of size 1 and 2 for single-end and paired-end data,
              respectively.
output:
    - sam:
          type: file
          description: Output SAM file containing read alignments
          pattern: "*.{sam}"
    - version:
          type: file
          description: File containing software version
          pattern: "*.{version.txt}"
    - log:
        type: file
        description: Aligment log
        pattern: "*.log"
authors:
    - "@joseespinosa"
    - "@drpatelh"
